{% set name = "aicsimageio" %}
{% set version = "4.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 075c75ea4accf417b2e312f65192a4af8b71eba16cdeaecbf90942085d1530ef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner >=5.2
  run:
    - python >=3.7
    - dask >=2021.4.1
    - fsspec >=2021.4.0
    - imagecodecs >=2020.5.30
    - lxml >=4.6
    - numpy >=1.16
    - ome-types >=0.2
    - tifffile >=2021.6.6
    - wrapt
    - xarray >=0.16.1
    - zarr >=2.6

    # Extra Formats (included by default)
    # [base-imageio]
    - imageio
    - imageio-ffmpeg
    - psutil


test:
  imports:
    - aicsimageio

about:
  home: https://github.com/AllenCellModeling/aicsimageio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image Reading, Metadata Conversion, and Image Writing for Microscopy Images in Pure Python
  doc_url: https://allencellmodeling.github.io/aicsimageio/index.html
  dev_url: https://github.com/AllenCellModeling/aicsimageio

extra:
  recipe-maintainers:
    - JacksonMaxfield
    - toloudis
    - tlambert03
